##### 菜鸟教程-笔记

* random 模块常用需求
```
print( random.randint(1,10) )        # 产生 1 到 10 的一个整数型随机数
print( random.random() )             # 产生 0 到 1 之间的随机浮点数
print( random.uniform(1.1,5.4) )     # 产生  1.1 到 5.4 之间的随机浮点数，区间可以不是整数
print( random.choice('tomorrow') )   # 从序列中随机选取一个元素
print( random.randrange(1,100,2) )   # 生成从1到100的间隔为2的随机整数
```

```
a = [1, 3, 5, 6, 7]          # 将序列a中的元素顺序打乱
random.shuffle(a)
print(a)

```

In [29]:
import random
import numpy as np
random.seed(a=1)    # 给是随机数设种子，方便复现结果！
ls1 = [random.uniform(1, 5) for i in range(5)]
len_ls = len(ls1)
a = np.array(ls1)
print(a, '\n', a.shape, '\n')

[ 1.53745698  4.38973495  4.05509848  2.0202761   2.98174035] 
 (5,) 



* 广播 [(参考链接)](https://blog.csdn.net/yangnanhai93/article/details/50127747)

In [31]:
a_col = a + np.zeros((5, 1))
print(a_col, '\n')

[[ 1.53745698  4.38973495  4.05509848  2.0202761   2.98174035]
 [ 1.53745698  4.38973495  4.05509848  2.0202761   2.98174035]
 [ 1.53745698  4.38973495  4.05509848  2.0202761   2.98174035]
 [ 1.53745698  4.38973495  4.05509848  2.0202761   2.98174035]
 [ 1.53745698  4.38973495  4.05509848  2.0202761   2.98174035]] 



In [32]:
# 对a转置，
aT = a.reshape(5, 1)
aT_row = aT + np.zeros((1, 5))
print(aT_row, '\n')

[[ 1.53745698  1.53745698  1.53745698  1.53745698  1.53745698]
 [ 4.38973495  4.38973495  4.38973495  4.38973495  4.38973495]
 [ 4.05509848  4.05509848  4.05509848  4.05509848  4.05509848]
 [ 2.0202761   2.0202761   2.0202761   2.0202761   2.0202761 ]
 [ 2.98174035  2.98174035  2.98174035  2.98174035  2.98174035]] 



In [39]:
# 对 a, a.T 做差
delta_a = a_col - aT_row
print(delta_a, '\n')


[[ 0.          2.85227797  2.5176415   0.48281913  1.44428337]
 [-2.85227797  0.         -0.33463647 -2.36945884 -1.4079946 ]
 [-2.5176415   0.33463647  0.         -2.03482237 -1.07335813]
 [-0.48281913  2.36945884  2.03482237  0.          0.96146425]
 [-1.44428337  1.4079946   1.07335813 -0.96146425  0.        ]] 



In [40]:
# 左下三角置0
for i in range(len_ls):
	for j in range(i, len_ls):
		delta_a[j, i] = 0
print(delta_a, '\n')

[[ 0.          2.85227797  2.5176415   0.48281913  1.44428337]
 [ 0.          0.         -0.33463647 -2.36945884 -1.4079946 ]
 [ 0.          0.          0.         -2.03482237 -1.07335813]
 [ 0.          0.          0.          0.          0.96146425]
 [ 0.          0.          0.          0.          0.        ]] 



In [41]:
# 取绝对值 & 返回最大值
delta_a = np.abs(delta_a)
print(delta_a, '\n')

print(np.max(delta_a), '\n')



[[ 0.          2.85227797  2.5176415   0.48281913  1.44428337]
 [ 0.          0.          0.33463647  2.36945884  1.4079946 ]
 [ 0.          0.          0.          2.03482237  1.07335813]
 [ 0.          0.          0.          0.          0.96146425]
 [ 0.          0.          0.          0.          0.        ]] 

2.8522779713 



In [43]:
# 返回np矩阵中，最大值的横纵轴索引
x, y = np.where(delta_a == np.max(delta_a)) + np.array([1])
print(x, y)
print(np.where(delta_a == np.max(delta_a)))

[1] [2]
(array([0], dtype=int32), array([1], dtype=int32))
